spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springjpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 실행때마다 기존 테이블 지우고 새로 생성
    properties:
      hibernate:
#        show_sql: true 시스템아웃 로그만 찍히기 때문에 주석.
        format_sql: true
        default_batch_fetch_size: 100
   # open-in-view: false  orderList.html에서 에러나서 주석처리.

logging:
  level:
    org.hibernate.SQL: debug  # 시스템아웃이 아닌 로그로 찍힌걸 보여주므로 이거 사용.
    org.hibernate.type: trace